# Use postgres/example user/password credentials
# version: '3'
services:
  db:
    image: mongo:latest
    hostname: notifications_db
    environment:
      - MONGO_INITDB_DATABASE=notifications_db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    logging:
      driver: none
    
  web:
    build: ./web_server
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./web_server/:/app/
    ports:
      - 8000:8000
    environment:
      - DATABASE_URI=postgresql://admin:admin@notifications_db/postgres_db_container
    depends_on:
      - db
  
  
